apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{.Release.Name}}-backend'
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: '{{.Release.Name}}-backend'
  template:
    metadata:
      labels:
        app: '{{.Release.Name}}-backend'
    spec:
      containers:
        - name: main
          image: ghcr.io/ondrejsika/counter
          resources:
            requests:
              cpu: 20m
              memory: 30Mi
            limits:
              cpu: 50m
              memory: 60Mi
          env:
            - name: REDIS
              value: '{{.Release.Name}}-redis'
            - name: SLOW_START
              value: '20'
            {{ if .Values.EXTRA_TEXT }}
            - name: EXTRA_TEXT
              value: '{{ .Values.EXTRA_TEXT }}'
            {{- end }}
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /readyz
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 1
          livenessProbe:
            httpGet:
              path: /livez
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
