{{ if .Values.backendHost }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{.Release.Name}}-backend'
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - '{{ .Values.backendHost }}'
      secretName: '{{ .Values.backendHost }}-tls'
  rules:
    - host: '{{ .Values.backendHost }}'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: '{{.Release.Name}}-backend'
                port:
                  number: 80
{{ end }}
