apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{.Release.Name}}-frontend'
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - '{{ .Values.frontendHost }}'
      secretName: '{{ .Values.frontendHost }}-tls'
  rules:
    - host: '{{ required ".Values.frontendHost is required" .Values.frontendHost }}'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: '{{.Release.Name}}-frontend'
                port:
                  number: 80
